baseURL = 'https://reader-blog.slax.com/'
languageCode = 'en-us'
title = 'Slax Reader blog'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
